config/routes.rb
GDS::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :companies, only: [:new, :create, :edit, :update, :destroy]
  resources :votes, only: [:create]
  resources :dislikes, only: [:create]
  resources :likes, only: [:create]
  resources :discussions, except: [:index]
  resources :questions, only: [:create]
  resources :arguments, only: [:create]
  resources :discussions_users, only: [:destroy, :create]
  resource :visual_aids, only: [:create]
  resources :discussion_state, only: [:update]
  resources :evaluations, only: [:show]
  resources :additional_user_fields, only: [:new, :create, :destroy, :edit, :index]
  resources :user_field_options, only: [:new, :create, :destroy]

  get '/users/new' => redirect('/users/sign_up')

  devise_for :users, :controllers => { :invitations => 'users_invitations', :registrations => "registrations" }
  resources :users, only: [:index, :create, :show, :edit, :update, :destroy]

  get '/new_customer' => 'users#new_customer'

  get 'discussions/:id/execute' => 'discussions#execute'

  get '/profile' => 'dashboard#show'
  get '/discussions' => redirect('/profile')
  get '/discussions/:id/users' => 'discussions#users'
  root 'static_pages#home'

  get '/users/:id/additional_informations' => 'users#additional_informations'
  post '/users/:id/additional_informations' => 'users#create_additional_informations'
  get '/imprint' => 'static_pages#imprint'
  get '/contact_us' => 'static_pages#contact_us'
  get 'eligibility_requirements' => 'static_pages#eligibility_requirements'

  get '/survey' => 'surveys#new'
  post '/survey' => 'surveys#create'
  get '/survey/result' => 'surveys#show', as: 'survey_result'

  post '/contact_us/send_mail' => 'static_pages#send_contact_mail'

  post '/discussions/:id/leave' => 'discussions#leave'
  post '/discussions/:id/enter' => 'discussions#enter'
  post '/discussions_users/:id/confirm' => 'discussions_users#confirm'

  post '/visual_aids/:id/open' => 'visual_aids#open'
  post '/visual_aids/:id/command' => 'visual_aids#command'
  post '/visual_aids/:id/close' => 'visual_aids#close'
  get '/discussions/:id/arguments' => 'discussions#arguments'
  delete 'visual_aids/:id' => 'visual_aids#destroy'

  get '/user_leaved/:id' => 'discussions#user_leaved'
  get '/user_entered/:id' => 'discussions#user_entered'

  get '/assets/faye-browser-min.js.map' => ->(*){ [200, {}, [""]] }
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_authorization_check


  def send_contact_mail
    ContactMailer.contact_us(params[:sender_name], params[:sender_email][0], params[:content]).deliver
  end

  def home
    if current_user
      redirect_to '/profile'
    end
  end

  def contact_us

  end

  def imprint
  end

  def eligibility_requirements

  end

  def contact_us_params
    params.require(:contact_us).permit(:sender_name, :sender_email, :content)
  end
end

app/views/static_pages/_companies.html.erb
<div id="companies-teaser">
  <div class="teaser-div companies-teaser center-block" data-page="1">
    <div class="teaser-width">
      <%= image_tag("home/companies.jpg") %>

      <div class="teaser-description">
        <h2>Strategieplanung mit Fundament</h2>
        <p>Sie haben eine neue Idee und möchten diese gemeinsam mit Ihren Kunden zielgerichtet und effektiv weiterentwickeln? Sie fragen sich, wie Ihr Konzept z.B. von Investoren oder einer bestimmten Kundengruppe bewertet wird?  Mit GDS bieten wir Ihrem Unternehmen erstmals die Möglichkeit, auf wissenschaftlicher Grundlage zielgruppenspezifische Analysen durchführen zu lassen. Ob Idea Validation, direktes korrespektives Feedback oder klassische Marktforschung, mit GDS erhalten Sie genau die Informationen, die Sie brauchen – und das einfacher, schneller und preiswerter als je zuvor!

           <!--Nähere Informationen zu unserem Konzept finden Sie hier.-->
        </p>
        <%= link_to 'Kontakt', '/contact_us', class: "btn btn-default btn-sm" %> 
        <%= link_to 'Diskussion buchen', '/new_customer', class: "btn btn-default btn-sm" %>
      </div>
    </div>
  </div>
  <div class="teaser-div companies-teaser center-block" data-page="2">
    <div class="teaser-width">
      <div class="teaser-left">
        <h2>Ihre Vorteile mit GDS:</h2>
        <h3>Wissenschaftliche Online-Diskussionen</h3>
        <p>Um den hohen wissenschaftlichen Standard von GDS zu erfüllen, haben wir viel Herzblut und Expertise in die
          Konzeption und Gestaltung unserer Diskussionsumgebung investiert. Das Resultat ist eine Umgebung, die optimal
          auf die Bedürfnisse Ihrer wissenschaftlichen Online-Diskussion abgestimmt ist.</p>

        <h3>Optimale Diskussionsteilnehmer </h3>
        <p>Wir bieten Ihnen optimale Diskussionsteilnehmer! Wir erheben zusätzlich zu den bisher genutzten
          Klassifizierungen anhand von soziodemografischen Merkmalen (Alter, Geschlecht, etc.) auch
          Persönlichkeitsmerkmale. Anhand dieser Daten können wir Ihre Teilnehmer Ihren Bedürfnissen entsprechend auswählen.</p>
      </div>
      <div class="teaser-right">
        <h3>Persönlichkeitstest</h3>
        <p>Unsere Probanden werden durch einen psychologischen Test klassifiziert. Bei dem Test handelt es sich um ein
          wissenschaftliches Messwerkzeug, das konstruiert wurde, um eine bestmögliche Klassifizierung der Probanden zu
          gewährleisten. Er entspricht den psychologischen Test-Güte-Kriterien.
        </p>

        <h3>Transparenz und Vertrauen</h3>
        <p>Durch unser Pay-per-Use Prinzip haben Sie stets volle Kontrolle über Ihre Kostenplanung. Wir kümmern uns von
          Beginn an um Ihre Anliegen und sehen uns als Partner an Ihrer Seite.</p>

        <h3>Marktforschung mit Begeisterung</h3>
        <p>Lassen Sie uns Ihr nächstes Projekt gemeinsam gestalten. Denn wir von GDS leben Marktforschung!</p>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_moderators.html.erb
<div id="moderators-teaser">
  <div class="teaser-div moderators-teaser center-block" data-page="1">
    <div class="teaser-width">
      <%= image_tag("home/moderators.jpg") %>

      <div class="teaser-description">
        <h2>Marktforschung mit Köpfchen</h2>
        <p>Wir sind stetig auf der Suche nach qualifizierten Moderatoren, denn nur mit den Besten an Board sind wir gut genug!
          So können wir unseren Partnern eine zielgerichtete Moderation auf höchstem Niveau bieten und beste Ergebnisse erzielen.
          Sie wollen Teil unseres Teams werden? Dann registrieren Sie sich noch heute.</p>
        <% if Rails.env.production? %>
          <%= link_to 'Kontakt', '/contact_us', class: "btn btn-default btn-sm" %>
        <% else %>
          <%= link_to 'Jetzt registrieren', '#', class: "btn btn-default btn-sm" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_our_service.html.erb
<div id="our-service-teaser">
  <div class="teaser-div our-service-teaser center-block" data-page="1">
    <div class="teaser-width">
      <%= image_tag("home/our_service.jpg") %>

      <div class="teaser-description">
        <h2>Gemeinsam in die Zukunft</h2>
        <p>Mit Group Discussion Services, dem tool für Ihre Online-Gruppendiskussionen, betreiben Sie präzise und wissenschaftlich fundierte Marktforschung. Mit uns haben Sie den starken Partner an Ihrer Seite, der Sie von Anfang an begleitet. Gruppendiskussionen mit optimalen Teilnehmern von zertifizierten Moderatoren auf höchstem Niveau betreut, das ist unser Schlüssel zu Ihrem Erfolg.</p>
        <br>
        <p>Lassen Sie uns gemeinsam die Zukunft gestalten!</p>
        <%= link_to 'Diskussion buchen', '/new_customer', class: "btn btn-default" %>
        <%= link_to 'Proband werden', users_new_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_probands.html.erb
<div id="probands-teaser">
  <div class="teaser-div probands-teaser center-block" data-page="1">
    <div class="teaser-width">
      <%= image_tag("home/probands_01.jpg") %>

      <div class="teaser-description">
        <h2>Ihre Meinung zählt</h2>
        <p>Mit GDS nehmen Sie bequem von zu Hause aus an Online-Gruppendiskussionen teil. Profitieren Sie von einer Aufwandsentschädigung (10 Euro pro Diskussion) sowie der Möglichkeit, direkten Einfluss auf wichtige Entscheidungen zu nehmen.  Um Sie zu den optimalen Diskussionsthemen einladen zu können, werden Sie im Rahmen Ihrer Registrierung unter anderem einen psychologischen Persönlichkeitstest ausfüllen, dessen Ergebnisse Sie als Dankeschön für Ihre Registrierung per Mail erhalten. Ihre Daten werden selbstverständlich anonymisiert behandelt.  Registrieren Sie sich jetzt als Proband und helfen Sie uns, den Markt der Zukunft mitzugestalten!</p>
          <!--<p class="hidden"><b>Unter allen Anmeldungen bis zum 30.06.2015 verlosen wir als Dankeschön ein iPad mini! <a href="/eligibility_requirements">Teilnahmebedingungen</a></b></p>-->
        <%= link_to 'Jetzt registrieren', new_user_registration_path, class: "btn btn-default btn-sm" %>
      </div>
    </div>
  </div>
  <div class="teaser-div probands-teaser center-block" data-page="2">
    <div class="teaser-width">
      <%= image_tag("home/probands_02.jpg") %>

      <div class="teaser-description">
        <p>Sie möchten Ihrer Stimme Gewicht verleihen? Mit GDS macht Marktforschung Spaß, denn wir bieten Ihnen
          interessante Diskussionsthemen. Bei uns wird mit Präzision und Hingabe gearbeitet, eine angenehme
          Arbeitsatmosphäre ist garantiert. Kommen Sie zu GDS und leben Sie Markforschung!</p>
        <%= link_to 'Jetzt registrieren', new_user_registration_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_research_institutes.html.erb
<div id="research-institutes-teaser">
  <div class="teaser-div research-institutes-teaser center-block" data-page="1">
    <div class="teaser-width">
      <%= image_tag("home/research_institutes.jpg") %>

      <div class="teaser-description">
        <h2>Innovative Marktforschung</h2>
        <p>Sie betreiben bereits aktiv Marktforschung, nutzen jedoch quantitative Erhebungsverfahren, die der Heterogenität der sozialen Lagen und den individuellen sowie prototypischen Persönlichkeitsmerkmalen einer Zielgruppe nicht gerecht werden? Die Lösung: Group Discussion Services – Die Gruppendiskussion auf einem neuen Level!  
        <br>Mit GDS bieten wir Ihnen die Möglichkeit, ein innovatives und effektives Erhebungswerkzeug in Ihr Methodenrepertoire aufzunehmen – und das ohne finanzielles Risiko. Durch unser Pay-per-Use-Prinzip sind Kosten und Leistungen jederzeit transparent.   
        <br>Profitieren auch Sie von den Vorteilen von GDS!
 </p>
          <%= link_to 'Kontakt', '/contact_us', class: "btn btn-default btn-sm" %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/contact_us.erb
<% title 'Kontakt' %>

<h1>Kontaktieren Sie uns!</h1>

<%= form_tag('/contact_us/send_mail', html: { multipart: true, role: "form"  }) do %>
  <div class="form-group">
    <%= label_tag(:sender_name, "Ihr Name") %>
    <%= text_field_tag(:sender_name, "", class: "form-control") %>
  </div>

  <div class="form-group">
    <%= label_tag(:sender_email, "Ihre Email Adresse") %>
    <%= email_field(:sender_email, "", class: "form-control") %>
  </div>

  <div class="form-group">
    <%= label_tag(:content, "Ihre Nachricht an uns" ) %>
    <%= text_area_tag(:content, "", class: "form-control", rows: 10) %>
  </div>

  <%= submit_tag("Email senden", class:"btn btn-default") %>
<% end %>

app/views/static_pages/eligibility_requirements.html.erb
	
<h1>Allgemeine Teilnahmebedingungen für Gewinnspiele und Preisausschreibenin den Angeboten von Psychomatix UG (haftungsbeschränkt).</h1>


<h2>1. Veranstalter, Geltungsbereich und Anerkennung der allgemeinen Teilnahmebedingungen</h2>
<p>
(1) Diese Allgemeine Bedingungen gelten für die Teilnahme an den Gewinnspielen, Preisausschreiben und Verlosungen, die in den Angeboten von Psychomatix UG (haftungsbeschränkt), veranstaltet werden. Das Angebot der Psychomatix UG umfasst insbesondere Multimediaanwendungen und Online-Medien.
</p>
<p>
(2) Psychomatix UG behält sich vor, für einzelne Gewinnspiele besondere Teilnahmebedingungen aufzustellen. Diese sind dann auf der jeweiligen Gewinnspielaktionsseite im Internet von Psychomatix UG einsehbar.
</p>
<p>
(3) Die Gewinnspiele werden von der Psychomatix UG (nachstehend „Psychomatix“ genannt), Rudolf-Breitscheid-Straße 187, 14482 Potsdam veranstaltet. Sofern ein Kooperationspartner vpn Psychomatix Mitveranstalter ist, wird dieser jeweils ausdrücklich genannt. Mitteilungen an Psychomatix erfolgen via E-Mail an folgende E-Mail-Adresse: info@group-discussion-services.de
</p>
<p>
(4) Mit der Teilnahme an einem Gewinnspiel, das Psychomatix in seinen Angeboten veranstaltet, erkennt der Teilnehmer ausdrücklich und verbindlich diese Allgemeinen Teilnahmebedingungen an.
</p>
<p>(5) Im Folgenden umfasst der Begriff „Gewinnspiel“ sowohl Gewinnspiele als auch Verlosungen und Preisausschreiben.
</p>
<h2>2. Teilnahmeberechtigung</h2>
<p>
(1) Teilnahmeberechtigt sind alle natürlichen Personen, die das 18. Lebensjahr vollendet und ihren ständigen Wohnsitz in der Bundesrepublik Deutschland haben.
</p>
<p>
(2) Von der Teilnahme ausgeschlossen sind Mitarbeiter von Psychomatix, Mitarbeiter von Kooperationspartnern des jeweiligen Gewinnspiels und alle Personen, welche mit der Durchführung des jeweiligen Gewinnspiels beschäftigt sind oder waren. Gleiches gilt für Angehörige (§15 Abgabenordnung) ersten und zweiten Grades dieser Personen sowie deren Lebenspartner in eheähnlicher Gemeinschaft.
</p>
<p>
(3) Jede Person darf nur einmal am Gewinnspiel teilnehmen.
</p>
<p>
(4) Die Teilnahme an dem Gewinnspiel ist nicht an den Kauf einer Ware, einer Dienstleistung, einer Spende oder Vergleichbares gebunden.
</p>
<h2>3. Ablauf des Gewinnspiels</h2>
<p>
Über den Ablauf des jeweiligen Gewinnspiels wird der Teilnehmer in dem jeweiligen Angebot von Psychomatix, ggf. auch in besonderen Teilnahmebedingungen (siehe unter Ziffer 1) informiert. Dies betrifft u.a. Beginn und Ende des Spiels, Teilnahme- und Auswahlverfahren, eventuelle Gewinnfragen bzw. -aufgaben.
</p>
<h2>4. Teilnahme über Telefon/Kosten</h2>
<p>
Eine Teilnahme ist je nach Gewinnspiel schriftlich, online, oder über die im jeweiligen Angebot genannte(n) Telefonnummer(n) möglich.

Ein Anruf auf der lokalen Studiohotline mit der Vorwahl 0331 aus dem Festnetz der Deutschen Telekom ist zum City- bzw. Ferntarif möglich. Im Übrigen richtet sich die Tarifierung nach dem vom Teilnehmer genutzten Verbindungsweg (Netz/Provider).

Verbindungskosten kommen erst ab dem Zeitpunkt zustande, nachdem der Anruf des Teilnehmers entgegengenommen (ggf. durch einen Anrufbeantworter) wurde. Hört der Teilnehmer ein Besetztzeichen oder einen Rufton, entstehen keine Kosten.

Bitte kontrollieren Sie Ihr Telefonverhalten, um unvorhergesehenen Kosten vorzubeugen.
</p>
<h2>5. Gewinn</h2>
<p>
Bei Sachpreisen ist eine Barauszahlung des Gewinnwertes bzw. ein Umtausch des Gewinns ausgeschlossen. Der Gewinnanspruch ist nicht übertragbar.

Wenn im Angebot nicht anders mitgeteilt, wird der Sachpreis dem Gewinner kostenfrei zugestellt.

Der Gewinnanspruch erlischt bei Nichterreichbarkeit des Gewinners, bei ausbleibender Rückmeldung des Gewinners oder bei Nichtannahme des Gewinns durch den Gewinner nach Ablauf von 21 Tagen, gerechnet ab der ersten Veröffentlichung des Gewinners durch Psychomatix.

Gewinne, die gemäß Angebot von Kooperationspartnern bzw. Preissponsoren gestellt werden, bietet Psychomatix nur in deren Namen an. Psychomatix ist in solchen Fällen nicht verantwortlich für die rechtzeitige und vollständige Ausschüttung des Gewinns sowie für Sach- bzw. Rechtsmängel oder für die Zahlungsunfähigkeit des Kooperationspartners und die daraus resultierenden Folgen für das Gewinnspiel.

Der in der Gewinnspielbeschreibung von Psychomatix gegebenenfalls bildlich oder mündlich präsentierte Gewinn, ist nicht zwingend mit dem zu gewinnenden Gegenstand identisch. Abweichungen insbesondere im Modell, Farbe und Ausstattung u. ä. sind möglich.
</p>
<h2>6. Ausschluss von Teilnehmern</h2>
<p>
Psychomatix behält sich vor, Teilnehmer von der Teilnahme am Gewinnspiel auszuschließen. Dies gilt insbesondere bei schuldhaften Verstößen gegen die Teilnahmebedingungen oder falls Teilnehmer den Teilnahmevorgang oder das Spiel manipulieren bzw. versuchen zu manipulieren oder sich anderer unredlicher Hilfsmittel bedienen.

Psychomatix kann Teilnehmer ausschließen, bei denen der begründete Verdacht besteht, dass diese sich in den Angeboten oder Veranstaltungen von Psychomatix (z.B. Gewinnergespräch mit dem Moderator) in strafbarer, insbesondere in ehrverletzender oder volksverhetzender Weise äußern werden.
</p>
<h2>7. Ausschluss von der Ausschüttung des Gewinns</h2>
<p>
Stellt Psychomatix nachträglich fest, dass der Teilnehmer einem im Sinne von Ziff. 6 zum Ausschluss führenden Grund verwirklicht hat bzw. nicht teilnahmeberechtigt im Sinne der Ziff. 2 war, kann Psychomatix diesen von der Ausschüttung des Gewinns ausschließen.
</p>
<h2>8. Veröffentlichung von Namen; Promotion</h2>
<p>
Psychomatix darf den Namen des Gewinners öffentlich im Programm oder auf den Internetseiten von Psychomatix bekannt geben, es sei denn, der Gewinner widerspricht ausdrücklich einer Veröffentlichung.

Der Gewinner verpflichtet sich, in vertretbarem Rahmen kostenfrei für Audio-, Foto-, Bild- und Textpromotion im Hörfunk, Internet oder gedruckten Veröffentlichungen zur Verfügung zu stehen und willigt einer dem Gewinnspielverlauf zweckgebunden entsprechenden Veröffentlichung seines Beitrages, in Wort, Bild oder Text, zu.
</p>
<h2>9. Abbruch Gewinnspiel</h2>
<p>
Psychomatix behält sich vor, das Gewinnspiel jederzeit abzubrechen oder zu beenden. Dies gilt insbesondere bei höherer Gewalt oder falls das Gewinnspiel aus anderen organisatorischen, technischen oder rechtlichen Gründen nicht durchgeführt bzw. fortgesetzt werden kann. Den Teilnehmern stehen in einem solchen Fall keine Ansprüche gegen Psychomatix zu.
</p>
<h2>10. Haftung</h2>
<p>
(1) Psychomatix haftet nicht für falsche Informationen, die die durch Teilnehmer und/oder Dritte, inklusive etwaiger Kooperationspartner von Psychomatix geäußert und verbreitet werden und die mit der Verbreitung von Informationen zum Gewinnspiel im Zusammenhang stehen.
</p>
<p>
(2) Psychomatix übernimmt keine Gewähr dafür, dass alle Verlinkungen und Verweise, die im Rahmen des Gewinnspiels getätigt werden richtig bzw. vollständig sind.
</p>
<p>
(3) Psychomatix haftet nicht für Schäden aufgrund von Störungen technischer Anlagen, für Verzögerungen oder Unterbrechungen von Übertragungen oder für Schäden, die im Zusammenhang mit der Teilnahme am Gewinnspiel bzw. mit der Annahme und der Nutzung des Gewinns stehen, es sei denn, Psychomatix bzw. dessen Erfüllungsgehilfen handeln vorsätzlich oder grob fahrlässig. Hiervon unberührt bleiben etwaige Ersatzansprüche aufgrund der Verletzung von Leben, Körper und Gesundheit sowie von wesentlichen Vertragspflichten.
</p>
<h2>11. Verhältnis mündliche Angaben/ schriftliche Teilnahmebedingungen</h2>
<p>
Weichen mündliche Angaben in den Angeboten (z.B. in der Moderation) inhaltlich von den vorstehenden Allgemeinen Teilnahmebedingungen oder von den Teilnahmebedingungen einzelner Gewinnspiele ab, so gelten bezüglich der abweichenden Angaben ausschließlich die Regelungen der Allgemeinen Teilnahmebedingungen bzw. der schriftlichen Teilnahmebedingung des jeweiligen Gewinnspiels.
</p>
<h2>12. Änderung der Teilnahmebedingungen</h2>
<p>Psychomatix behält sich vor, jederzeit die Teilnahmebedingungen zu ändern.</p>
<h2>13. Datenschutz</h2>
<p>
Alle personenbezogenen Daten des Teilnehmers werden ausschließlich zum Zwecke der Durchführung und Abwicklung des Gewinnspiels gespeichert und genutzt. Eine unberechtigte Weitergabe an Dritte findet nicht statt. Ebenso eine Nutzung für Werbezwecke. Nach Abschluss des Gewinnspiels werden die Daten der Teilnehmer unverzüglich gesperrt und innerhalb der technisch vorgegebenen Routinen anschließend gelöscht. Es steht jedem Teilnehmer frei, seine Teilnahme am Gewinnspiel sowie seine Einwilligung zur Speicherung und Verwendung seiner Daten zu widerrufen. Der Widerruf ist zu richten an friedrich@psychomatix.de.

Mit der Löschung der Daten ist die Teilnahme am Gewinnspiel und einer ggf. nachfolgenden Verlosung ausgeschlossen.
</p>
<h2>14. Schlussbestimmungen</h2>
<p>
(1) Es gilt das Recht der Bundesrepublik Deutschland.
</p>
<p>
(2) Abweichungen von diesen Teilnahmebedingungen bedürfen zu Ihrer Wirksamkeit der Schriftform. Das gleiche gilt hinsichtlich der Abbedingungen des Schriftformerfordernisses.
</p>
<p>
(3) Sollten eine oder mehrere der vorstehenden Klauseln ganz oder teilweise nichtig, unwirksam oder undurchführbar sein oder werden, bleiben die übrigen Bedingungen wirksam. An deren Stelle tritt eine entsprechende gültige Klausel. Gleiches gilt bei Vorliegen einer Regelungslücke.
</p>
<p>
(4) Erfüllungsort und Gerichtsstand ist Wetzlar, soweit eine Vereinbarung hierüber zulässig ist. Ansonsten gilt der Sitz bzw. Wohnsitz der beklagten Partei.
</p>
<p>
(5) Der Rechtsweg ist ausgeschlossen.
</p>
<h2>15. Gewinnspielanbieter</h2>
<p>
Anbieter des Gewinnspiels ist<br>
<br>
<adress>
<strong>Psychomatix UG 
(haftungsbeschränkt)</strong><br>

Rudolf-Breitscheid-Straße 187<br>
14482 Potsdam<br>
Deutschland<br>
<br>
Telefon: +49 (0)331 979 922 59<br>
Telefax: +49 (0)331 231 897 99<br>
E-Mail: friedrich@psychomatix.de<br>
Internet: www.group-discussion-services.de<br>
<br> 
Handelsregister - NR: HRB - 27688<br>
Registerort: Amtsgericht Potsdam<br>
<br>
Geschäftsführer:<br>
Lukas Waschat<br>
Tim Friedrich<br>
</adress>
<h2>16. Facebook-Disclaimer</h2>
<p>
Sofern Gewinnspiele auf Facebook nicht mittels einer Facebook-Applikation ausgeführt werden, gilt Facebook Ireland Limited Hanover Reach, 5-7 Hanover Quay, Dublin 2, Ireland, ausdrücklich weder als Ansprechpartner noch als in irgendeiner Weise in Zusammenhang stehend mit dem Gewinnspiel.
</p>
Stand: April 2014

app/views/static_pages/send_contact_mail.html.erb
<h2>Vielen Dank für Ihr Interesse.</h2><p> Wir bearbeiten Ihre Anfrage und melden uns schnellstmöglich bei Ihnen zurück.</p>