config/routes.rb
GDS::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :companies, only: [:new, :create, :edit, :update, :destroy]
  resources :votes, only: [:create]
  resources :dislikes, only: [:create]
  resources :likes, only: [:create]
  resources :discussions, except: [:index]
  resources :questions, only: [:create]
  resources :arguments, only: [:create]
  resources :discussions_users, only: [:destroy, :create]
  resource :visual_aids, only: [:create]
  resources :discussion_state, only: [:update]
  resources :evaluations, only: [:show]
  resources :additional_user_fields, only: [:new, :create, :destroy, :edit, :index]
  resources :user_field_options, only: [:new, :create, :destroy]

  get '/users/new' => redirect('/users/sign_up')

  devise_for :users, :controllers => { :invitations => 'users_invitations', :registrations => "registrations" }
  resources :users, only: [:index, :create, :show, :edit, :update, :destroy]

  get '/new_customer' => 'users#new_customer'

  get 'discussions/:id/execute' => 'discussions#execute'

  get '/profile' => 'dashboard#show'
  get '/discussions' => redirect('/profile')
  get '/discussions/:id/users' => 'discussions#users'
  root 'static_pages#home'

  get '/users/:id/additional_informations' => 'users#additional_informations'
  post '/users/:id/additional_informations' => 'users#create_additional_informations'
  get '/imprint' => 'static_pages#imprint'
  get '/contact_us' => 'static_pages#contact_us'
  get 'eligibility_requirements' => 'static_pages#eligibility_requirements'

  get '/survey' => 'surveys#new'
  post '/survey' => 'surveys#create'
  get '/survey/result' => 'surveys#show', as: 'survey_result'

  post '/contact_us/send_mail' => 'static_pages#send_contact_mail'

  post '/discussions/:id/leave' => 'discussions#leave'
  post '/discussions/:id/enter' => 'discussions#enter'
  post '/discussions_users/:id/confirm' => 'discussions_users#confirm'

  post '/visual_aids/:id/open' => 'visual_aids#open'
  post '/visual_aids/:id/command' => 'visual_aids#command'
  post '/visual_aids/:id/close' => 'visual_aids#close'
  get '/discussions/:id/arguments' => 'discussions#arguments'
  delete 'visual_aids/:id' => 'visual_aids#destroy'

  get '/user_leaved/:id' => 'discussions#user_leaved'
  get '/user_entered/:id' => 'discussions#user_entered'

  get '/assets/faye-browser-min.js.map' => ->(*){ [200, {}, [""]] }
end

app/models/additional_user_field.rb
class AdditionalUserField < ActiveRecord::Base
  has_many :user_additional_user_fields
  has_many :user_field_options

  def self.new_fields_for(user)
    new_fields = []
    AdditionalUserField.all.each do | field |
      puts field.to_yaml
      puts UsersAdditionalUserField.where(user_id: user.id, additional_user_field_id: field.id).empty?
      if UsersAdditionalUserField.where(user_id: user.id, additional_user_field_id: field.id).empty?
        new_fields << (field)
      end
    end
    return new_fields
  end

  def type_class
    return 'radio' if field_type == "single_select"
    return 'checkbox' if field_type == "multiple_select"
  end
end

app/controllers/additional_user_fields_controller.rb
class AdditionalUserFieldsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_additional_user_field, only: [:destroy, :edit]
  load_and_authorize_resource :discussion

  def new
    @additional_user_field = AdditionalUserField.new
  end

  def create
    @additional_user_field = AdditionalUserField.new(additional_user_field_params)

    respond_to do |format|
      if @additional_user_field.save
        format.html do 
          redirect_to edit_additional_user_field_path @additional_user_field
        end
      else
        format.html { render action: 'new' }
      end
    end
  end

  def index
    @additional_user_fields = AdditionalUserField.all.paginate(page: params[:additional_user_fields_page], per_page: 10)
  end

  def edit

  end

  def destroy
    @additional_user_field.user_field_options.each do | field |
      field.destroy
    end
    @additional_user_field.destroy
    redirect_to additional_user_fields_path
  end

  private

  def set_additional_user_field
    @additional_user_field = AdditionalUserField.find(params[:id])
  end

  def additional_user_field_params
    params.require(:additional_user_field).permit(:name, :field_type)
  end
end

app/views/additional_user_fields/_form.html.erb
<%= form_for(@additional_user_field) do |f| %>
  <%= render partial: "shared/error_messages", locals: { resource: @additional_user_field } %>
  <div class="form-group">
    <%= f.label :name, "Name", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :field_type, "Typ", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select "field_type", [["Einfach Auswahl", 'single_select'], ["Mehrfach Auswahl", 'multiple_select'], ["Numerischer Wert", 'integer']], {}, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit value: 'Speichern', class: "btn btn-large btn-primary" %>
    </div>
  </div>
<% end %>

app/views/additional_user_fields/edit.html.erb
<h1>Benutzerfeld: <%= @additional_user_field.name %></h1>

<%= render 'form'  %>

<h2>Neue Option</h2>

<%= form_tag('/user_field_options', html: { multipart: true, class: "form-horizontal", role: "form"  }) do %>

  <div class="form-group">
    <%= label_tag :values, "Optionen durch Zeilenumbruch trennen", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= text_area_tag :values, "", class: "form-control" %>
    </div>
  </div>
  <%= hidden_field_tag :additional_user_field_id, @additional_user_field.id %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= submit_tag "Hinzufügen", class: "btn btn-large btn-primary"%>
    </div>
  </div>
<% end %>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Option</th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @additional_user_field.user_field_options.each do |option| %>
    <tr>
      <td><%= option.value %></td>
      <td><%= link_to 'Löschen', option, method: :delete, data: { confirm: 'Sind Sie sicher?' }, class: "btn btn-xs btn-primary" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/additional_user_fields/index.html.erb
<h1>Benutzerfelder verwalten</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @additional_user_fields.each do |user_field| %>
    <tr>
      <td><%= user_field.name %></td>
      <td><%= link_to 'Bearbeiten', edit_additional_user_field_path(user_field), class: "btn btn-xs btn-primary" %></td>
      <td><%= link_to 'Löschen', user_field, method: :delete, data: { confirm: 'Sind Sie sicher?' }, class: "btn btn-xs btn-primary" %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @additional_user_fields, renderer: BootstrapPagination::Rails, param_name: 'additional_user_fields_page' %>

<%= link_to "Neues Benutzerfeld anlegen", new_additional_user_field_path, class: "btn btn-xs btn-primary" %>

app/views/additional_user_fields/new.html.erb
<h1>Neues Benutzerfeld Anlegen</h1>

<%= form_for(@additional_user_field) do |f| %>
  <%= render 'form' %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit value: 'Weiter', class: "btn btn-large btn-primary" %>
    </div>
  </div>
<% end %>