config/routes.rb
GDS::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :companies, only: [:new, :create, :edit, :update, :destroy]
  resources :votes, only: [:create]
  resources :dislikes, only: [:create]
  resources :likes, only: [:create]
  resources :discussions, except: [:index]
  resources :questions, only: [:create]
  resources :arguments, only: [:create]
  resources :discussions_users, only: [:destroy, :create]
  resource :visual_aids, only: [:create]
  resources :discussion_state, only: [:update]
  resources :evaluations, only: [:show]
  resources :additional_user_fields, only: [:new, :create, :destroy, :edit, :index]
  resources :user_field_options, only: [:new, :create, :destroy]

  get '/users/new' => redirect('/users/sign_up')

  devise_for :users, :controllers => { :invitations => 'users_invitations', :registrations => "registrations" }
  resources :users, only: [:index, :create, :show, :edit, :update, :destroy]

  get '/new_customer' => 'users#new_customer'

  get 'discussions/:id/execute' => 'discussions#execute'

  get '/profile' => 'dashboard#show'
  get '/discussions' => redirect('/profile')
  get '/discussions/:id/users' => 'discussions#users'
  root 'static_pages#home'

  get '/users/:id/additional_informations' => 'users#additional_informations'
  post '/users/:id/additional_informations' => 'users#create_additional_informations'
  get '/imprint' => 'static_pages#imprint'
  get '/contact_us' => 'static_pages#contact_us'
  get 'eligibility_requirements' => 'static_pages#eligibility_requirements'

  get '/survey' => 'surveys#new'
  post '/survey' => 'surveys#create'
  get '/survey/result' => 'surveys#show', as: 'survey_result'

  post '/contact_us/send_mail' => 'static_pages#send_contact_mail'

  post '/discussions/:id/leave' => 'discussions#leave'
  post '/discussions/:id/enter' => 'discussions#enter'
  post '/discussions_users/:id/confirm' => 'discussions_users#confirm'

  post '/visual_aids/:id/open' => 'visual_aids#open'
  post '/visual_aids/:id/command' => 'visual_aids#command'
  post '/visual_aids/:id/close' => 'visual_aids#close'
  get '/discussions/:id/arguments' => 'discussions#arguments'
  delete 'visual_aids/:id' => 'visual_aids#destroy'

  get '/user_leaved/:id' => 'discussions#user_leaved'
  get '/user_entered/:id' => 'discussions#user_entered'

  get '/assets/faye-browser-min.js.map' => ->(*){ [200, {}, [""]] }
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  STATES = %w[open closed]
  default_scope {order('due_date DESC')}

  has_many :questions
  has_many :arguments
  has_many :discussions_users
  has_many :users, through: :discussions_users
  has_many :visual_aids

  validates :due_date, presence: true
  validates :state, inclusion: { in: STATES }


  def probands
    DiscussionsUser.where(discussion: self, role: Role.proband)
  end

  def confirmed_probands
    confirmed_discussions_users.select { | discussions_user | discussions_user.role == Role.proband  }
  end

  def observers
    DiscussionsUser.where(discussion: self, role: Role.observer)
  end

  def customer
    DiscussionsUser.where(discussion: self, role: Role.customer).first.user if DiscussionsUser.where(discussion: self, role: Role.customer).first
  end

  def customer=(user)
    if self.customer
      DiscussionsUser.where(discussion: self, role: Role.customer).first.delete
    end
    discussions_user = discussions_users.build(
      user: user,
      discussion: self,
      role: Role.customer,
      confirmed: true,
    )
    discussions_user.save!
    discussions_user.set_name
  end

  def discussions_user_for(user)
    discussions_users.find_by(user: user)
  end

  def discussions_users_with_users
    discussions_users.includes(:role, user: [:role])
  end

  def current_question
    self.questions.last
  end

  def moderator
    discussions_users_with_users.find{ |user|
      user.role == Role.moderator
    }.try(:user)
  end

  def customer
    discussions_users_with_users.find{ |user|
      user.role == Role.customer
    }.try(:user)
  end

  def confirmed_discussions_users
    confirmed_users = []
    discussions_users.each do |discussions_user|
      if discussions_user.confirmed?
        confirmed_users << discussions_user
      end
    end
    return confirmed_users
  end

  def moderator=(user)
    moderator = discussions_user_for(moderator)
    moderator.delete if moderator
    if user
      discussions_user = discussions_users.build(
        user: user,
        role: Role.moderator,
        confirmed: true,
      )
      discussions_user.save!
      discussions_user.set_name
    end
  end

  def moderator_avatar
    moderator.avatar.present? ? moderator.avatar.url(:discussion) : image_path('Unknown-person.gif')
  end

  def open?
    state == 'open'
  end

  def closed?
    state == 'closed'
  end

  def open(message)
    self.state_message = message
    self.state = 'open'
    self.save!
  end

  def close(message)
    self.state_message = message
    self.state = 'closed'
    self.save!
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :set_discussion, except: [:new, :create, :users]
  before_filter :authenticate_user!
  load_and_authorize_resource


  def execute
    respond_to do |format|
      if !current_user.is_part_of_discussion?(@discussion)
        format.html{ redirect_to '/profile', notice: "Du bist nicht für diese Diskussion eingetragen" }
        format.json{ render status: :forbidden }
      elsif @discussion.closed?
        format.html{ render action: 'discussion_closed' }
        format.json{ render status: :forbidden }
      else
        @discussion_user = @discussion.discussions_user_for(current_user)
        current_user.enter_discussion(@discussion)
        PrivatePub.publish_to "/discussion/#{@discussion.id}/users/enter", user_id: current_user.id

        format.html{ @questions = Question.where(discussion_id: params[:id]) }
        format.json do
          @discussions_user = @discussion.confirmed_discussions_users
          @visual_aids_log = VisualAidsLog.where('visual_aid_id in (:visual_aids)', { visual_aids: @discussion.visual_aids.to_a.map(&:id) } )
          if current_user == @discussion.moderator or @discussion_user.role.name == 'observer'
            @arguments = @discussion.arguments.includes(:argument_type)
            @votes = Vote.where('argument_id in (:arguments)', { arguments: @arguments.to_a.map(&:id) })
          else
            @arguments = []

            @discussion.arguments.each do | argument |
              if argument.argument_type.name == 'proband' or argument.argument_type.name == 'moderator'
                @arguments.push(argument)
              end
            end
            @votes = Vote.where('argument_id in (:arguments) and user_id = :user', {arguments: @arguments.to_a.map(&:id), user: current_user})
          end
        end
      end
    end
  end

  def users
    respond_to do |format|
      format.html do
        bad_request        
      end
      format.json do
        
      end
    end
  end

  def show

  end

  def leave
    current_user.leave_discussion(@discussion)
    PrivatePub.publish_to "/discussion/#{@discussion.id}/users/leave", user_id: current_user.id
    render nothing: true
  end

  def new
    @discussion = Discussion.new
    @users = User.all
    @proband = DiscussionsUser.new
    if Company.all.any?
      @companies = Company.all
    else
      @companies = []
    end
  end

  def edit
    @probands    = @discussion.probands.paginate(page: params[:probands_page], per_page: 10)
    @observers   = @discussion.observers.paginate(page: params[:observers_page], per_page: 10)
    @visual_aids = @discussion.visual_aids.paginate(page: params[:visual_aids_page], per_page: 10)
    @moderators = User.moderators   

    respond_to do |format|
      format.html do
        session[:return_to] = profile_path
        @survey_texts = JSON.load(Rails.root.join 'db/survey_analysis_texts.json')
        @companies = Company.all
        @proband = DiscussionsUser.new role: Role.proband
        @visual_aid = VisualAid.new
        if current_user.role == Role.moderator || current_user.role == Role.admin
          @users = User.all
        elsif current_user.role == Role.extModerator   
          @users = []
        end
        @user = User.new
      end
      format.js do
        if @discussion.errors
          render json: @discussion.errors
        end
      end
    end
  end

  def create
    @discussion = Discussion.new(discussion_params)
    @question = Question.create(topic: "Herzlich Willkommen", discussion: @discussion)

    respond_to do |format|
      if @discussion.save
        @discussion.moderator = current_user if current_user.is_moderator? or current_user.is_admin?
        @discussion.customer = current_user if current_user.is_customer?
        @question.save
        DiscussionMailer.new_discussion(@discussion, current_user).deliver_now
        format.html do 
          if current_user.is_moderator? || current_user.is_admin?
            redirect_to edit_discussion_path(@discussion) 
          else
            redirect_to '/profile'
          end 
        end
        format.json { render action: 'show', status: :created, location: @discussion }
      else
        format.html { render action: 'new' }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      modified_params = discussion_params
      modified_params[:moderator] = User.find_by_id(discussion_params[:moderator])
      if @discussion.update(modified_params)
        format.html { redirect_to(session.delete(:return_to) || profile_path, notice: 'Die Diskussion wurde erfolgreich aktualisiert.') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    DiscussionsUser.where(discussion_id: @discussion.id).destroy_all
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to '/profile' }
      format.json { head :no_content }
    end
  end

  def arguments
    respond_to do | format |
      format.json{ render json: @discussion.arguments }
      format.html{ render json: @discussion.arguments }
    end
  end


  private

  def set_discussion
    @discussion = Discussion.find(params[:id])
  end

  def discussion_params
    params.require(:discussion).permit(:topic, :moderator, :due_date, :moderator_id, :users, :company_id, :company, :visual_aids, :summary, :description)
  end
end

app/views/discussions/_form.html.erb
<%= form_for(@discussion, html: { multipart: true, class: "form-horizontal", role: "form"  }) do |f| %>

  <%= render partial: "shared/error_messages", locals: { resource: @discussion } %>

  <% if @discussion.customer %>
    <div class="form-group">
      <%= f.label :Auftraggeber, class: "col-sm-2 control-label" %>
      <div class="col-sm-10 customer-name">
        <%= link_to @discussion.customer.full_name(), current_user %>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :topic, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :topic, class: "form-control" %>
    </div>
  </div>
  <% if current_user.is_admin? && false %>
    <div class="form-group">
      <%= f.label :moderator, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.collection_select :moderator, @moderators, :id, :full_name, {include_blank: true}, {class: "form-control"} %>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :due_date, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <div class="form-control datepicker-old">
        <%= f.datetime_select  :due_date, :value => (@discussion.due_date.blank? ? '' : @discussion.due_date.strftime('%d-%m-%Y-%H-%M'))%>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-large btn-primary"%>
    </div>
  </div>
<% end %>

app/views/discussions/_list_discussions.html.erb
<table class="table">
  <thead>
  <tr>
    <th>Thema</th>
    <th>Moderator</th>
    <th>Datum</th>
    <% if can? :manage, Discussion %><th></th><% end %>
    <th></th>
    <% if can? :edit, Discussion %><th></th><% end %>
    <% if can? :delete, Discussion %><th></th><% end %>
    <% if can? :evaluate, Discussion %><th></th><% end %>
  </tr>
  </thead>
  <tbody>
  <% discussions.each do |discussion| %>
    <tr>
      <td><%= discussion.topic %></td>
      <td><% if discussion.moderator %><%= discussion.moderator.firstname %> <%= discussion.moderator.lastname %><% end %></td>
      <td><%= l discussion.due_date %></td>
      <td id="discussion-toggle-button-<%= discussion.id %>">
        <%= render partial: 'discussion_state/toggle_state_button', locals: { discussion: discussion } %>
      </td>
      <td id="discussion-join-button-<%= discussion.id %>">
        <%= link_to 'Beitreten', "discussions/#{discussion.id}/execute", class: "btn btn-xs btn-primary", style: "display: #{discussion.closed? ? 'none' : 'inline-block'}" %>
      </td>
      <td><%= link_to 'Bearbeiten', edit_discussion_path(discussion), class: "btn btn-xs btn-primary" %></td>
      <td><%= link_to 'Löschen', discussion, method: :delete, data: { confirm: 'Sind Sie sicher?' }, class: "btn btn-xs btn-primary" %></td>
        <td><%= link_to 'Evaluation', evaluation_path(discussion), class: "btn btn-xs btn-primary" %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate discussions, renderer: BootstrapPagination::Rails, param_name: 'discussions_page' %>

app/views/discussions/_probands_selection.html.erb
<ul class="nav nav-pills nav-stacked" id="probands_nav">
  <li role="presentation" class="active"><a data-id="users_overview" href="#">Übersicht</a></li>
  <li role="presentation"><a data-id="invite_probands" href="#">Probanden Einladen</a></li>
  <li role="presentation"><a data-id="invite_observers" href="#">Beobachter einladen</a></li>
</ul>

<div id="users_overview">
  <h2>Teilnehmer</h2>
  <div class="message"></div>

  <div class="probands_list">
    <div st-table="displayedInvitedUsers" st-safe-src="invited_users">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Geschlecht</th>
            <th>Alter</th>
            <th>Schulabschluss</th>
            <th>Abschluss</th>
            <th>Einkommen</th>
            <th>Status</th>
            <th>Postleitzahl</th>
            <th>
          </tr>
        </thead>
        <tbody>
          <tr ng-repeat="user in displayedInvitedUsers" class="{{{true:'success', false:'danger'}[user.confirmed_discussion]}}">
            <td>{{user.gender}}</td>
            <td>{{user.age}}</td>
            <td>{{user.school}}</td>
            <td>{{user.degree}}</td>
            <td>{{user.income}}</td>
            <td>{{user.personal_status}}</td>
            <td>{{user.zipcode}}</td>
            <td><button ng-click="delete_invited_user(user)" class="btn btn-xs btn-primary">Löschen</button></td>
          </tr>
        </tbody>
        <tfoot>
          <tr>
            <td colspan="5" class="text-center">
              <div st-pagination="" st-items-by-page="itemsByPage" st-displayed-pages="7"></div>
            </td>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>

  <h2>Beobachter</h2>

  <div class="observers_list">
    <%= render partial: "discussions_users/list_users", locals: { discussions_users: @observers, id: "observers", page_name: "observers_page" } %>
  </div>
</div>

<div id="invite_probands">
  <div class="message"></div>

  <h2>Einladen über Email Adresse</h2>
  <p>Laden Sie Probanden über deren Email Adresse ein. Sie können auch Probanden die sich noch nicht registriert haben einladen.</p>

  <%= render partial: "discussions_users/email_invitation", locals: { discussions_users: @user, role: "proband" } %>
  <%= render partial: "discussions_users/invitation", locals: { survey_texts: survey_texts } %>
  
<div id="invite_observers">
  <div class="message"></div>
  <h2>Einladen über Email Adresse</h2>
  <p>Laden Sie Beobachter über deren Email Adresse ein. Sie können auch Beobachter die sich noch nicht registriert haben einladen.</p>
  <%= render partial: "discussions_users/email_invitation", locals: { discussions_users: @user, role: "observer" } %>

</div>

app/views/discussions/discussion_closed.html.erb
<% title 'Diskussion geschlossen' %>

<h1><%= @discussion.state_message %></h1>

<p><a href="/profile">Zum Profil.</a></p>

app/views/discussions/edit.html.erb
<% title 'Diskussion bearbeiten' %>
<div id="edit_discussion" ng-app="discussionEdit" ng-controller="DiscussionEditController" data-discussion-id="<%= @discussion.id %>">
  <h1>Diskussion bearbeiten</h1>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href="#general_informations" data-toggle="tab">Allgemeine Informationen</a></li>
    <li><a href="#invite_users" data-toggle="tab">Teilnehmer</a></li>
    <li><a href="#visual_aids" data-toggle="tab">Anschauungsmaterial</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div class="tab-pane fade in active" id="general_informations">

      <%= render 'form' %>
    </div>

    <div class="tab-pane fade" id="invite_users">
      <%= render partial: 'probands_selection', locals: { survey_texts: @survey_texts  } %>
    </div>


    <div class="tab-pane fade" id="visual_aids">

      <h2>Anschauungsmaterial</h2>

      <span class="btn btn-success fileinput-button disabled">
        <i class="glyphicon glyphicon-plus"></i>
        <span>Select files...</span>
        <input id="fileupload" type="file" name="files[]" multiple="">
        <input id="visual_aid_discussion_id" name="visual_aid[discussion_id]" type="hidden" value="<%= @discussion.id %>">
      </span>

      <div class="alert alert-danger hidden" id="not-supported-file" role="alert">Die der von Ihnen ausgewählte Dateityp wird nicht unterstützt. Bitte wählen sie eine Bilddatei oder Videodatei.</div>
      <div class="visual_aids_list">
        <% if @visual_aids != [] %>
          <%= render partial: "visual_aids/list", locals: { visual_aids: @visual_aids } %>
        <% end %>
      </div>
    </div>
  </div>

</div>
<% content_for :javascript do %>
  $(document).ready(function(){ init_edit_discussion(<%= @discussion.id %>) });
<% end %>

app/views/discussions/edit.js.erb
$(".probands_list").children().remove()
$(".probands_list").html('' +
'<%= escape_javascript(render partial: "discussions_users/list_users",
        locals: { discussions_users: @probands, id: "probands", page_name: "probands_page" }) %>')

$(".observers_list").children().remove()
$(".observers_list").html('' +
'<%= escape_javascript(render partial: "discussions_users/list_users",
        locals: { discussions_users: @observers, id: "observers", page_name: "observers_page" }) %>')

$(".visual_aids_list").children().remove()
$(".visual_aids_list").html('' +
'<%= escape_javascript(render partial: "visual_aids/list",
        locals: { visual_aids: @visual_aids }) %>')

$('.probands_list, .observers_list, .visual_aids_list').find('a').click(function(event) {
          $(event.target).parent().parent().remove();
        }
)

app/views/discussions/execute.html.erb
<% title 'Diskussion' %>

<div id="discussion">
  <div class="toolbox"></div>

  <div id="moderator">
    <div id="question"></div>
    <div id="moderator_show">
      <%= image_tag(@discussion.moderator_avatar, size: "60x60", alt: "Bild des Moderators") %>
    </div>
  </div>

  <div class="chat_container">

    <div id="chat">
      <div id="arguments"></div>
    </div>

    <%= form_for Argument.new, role: "form", remote: true do |f| %>
      <div class="form-group">
    	<div class="emoticon_picker"><span class="emoticon emoticon-smile" title="Smiley hinzufügen">:)</span>
          <div class="emoticon_prev" ></div>
        </div>
        <div contentEditable="true" class="form-control" id="new_argument_content"></div>

      </div>
      <%= f.hidden_field :discussion_id, value: @discussion.id %>
      <div id="submit_buttons">
        <% if @discussion.moderator == current_user %>
          <div class="btn-group">
            <button type="button" class="btn btn-default" id="new_argument_button">Senden</button>
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><a href="javascript:void(0);" id="new_question_button">Neue Frage</a></li>
              <li><a href="javascript:void(0);" id="new_observer_argument_button">An Beobachter senden</a></li>
            </ul>
          </div>
        <% else %>
          <%= f.submit "Senden" , class: "btn btn-success", id: "new_argument_button" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<% content_for :late_assets do %>
  <%= subscribe_to "/discussion/#{@discussion.id}/arguments/new" %>
  <% if current_user == @discussion.moderator || @discussion_user.role.name == 'observer' || @discussion_user.role.name == 'customer' %>
    <%= subscribe_to "/discussion/#{@discussion.id}/observer/arguments/new" %>
  <% end %>
  <%= subscribe_to "/discussion/#{@discussion.id}/questions/new" %>
  <%= subscribe_to "/discussion/#{@discussion.id}/visualAid/open" %>
  <%= subscribe_to "/discussion/#{@discussion.id}/visualAid/close" %>
  <%= subscribe_to "/discussion/#{@discussion.id}/votes/new" %>
  <%= subscribe_to "/discussion/#{@discussion.id}/users/new" %>
  <%= subscribe_to "/discussion/#{@discussion.id}/users/enter" %>
  <%= subscribe_to "/discussion/#{@discussion.id}/users/leave" %>
  <%= subscribe_to "/discussion/#{@discussion.id}/visualAid/command" %>
  <% unless current_user == @discussion.moderator %>
    <%= subscribe_to "/discussion/#{@discussion.id}/state/close" %>
  <% end %>
<% end %>

<% content_for :javascript do %>
  $(document).ready(function(){ new Discussion(); });
<% end %>

app/views/discussions/new.html.erb
<% title 'Neue Diskussion' %>
<h1>Neue Diskussion</h1>

<%= render 'form' %>

<div class="form-horizontal">
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= link_to 'Abbrechen', profile_path %>
    </div>
  </div>
</div>

app/views/discussions/show.html.erb
<h1><%= @discussion.topic %> <small><%= l @discussion.due_date %></small></h1>

<p><%= @discussion.description %></p>