config/routes.rb
GDS::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :companies, only: [:new, :create, :edit, :update, :destroy]
  resources :votes, only: [:create]
  resources :dislikes, only: [:create]
  resources :likes, only: [:create]
  resources :discussions, except: [:index]
  resources :questions, only: [:create]
  resources :arguments, only: [:create]
  resources :discussions_users, only: [:destroy, :create]
  resource :visual_aids, only: [:create]
  resources :discussion_state, only: [:update]
  resources :evaluations, only: [:show]
  resources :additional_user_fields, only: [:new, :create, :destroy, :edit, :index]
  resources :user_field_options, only: [:new, :create, :destroy]

  get '/users/new' => redirect('/users/sign_up')

  devise_for :users, :controllers => { :invitations => 'users_invitations', :registrations => "registrations" }
  resources :users, only: [:index, :create, :show, :edit, :update, :destroy]

  get '/new_customer' => 'users#new_customer'

  get 'discussions/:id/execute' => 'discussions#execute'

  get '/profile' => 'dashboard#show'
  get '/discussions' => redirect('/profile')
  get '/discussions/:id/users' => 'discussions#users'
  root 'static_pages#home'

  get '/users/:id/additional_informations' => 'users#additional_informations'
  post '/users/:id/additional_informations' => 'users#create_additional_informations'
  get '/imprint' => 'static_pages#imprint'
  get '/contact_us' => 'static_pages#contact_us'
  get 'eligibility_requirements' => 'static_pages#eligibility_requirements'

  get '/survey' => 'surveys#new'
  post '/survey' => 'surveys#create'
  get '/survey/result' => 'surveys#show', as: 'survey_result'

  post '/contact_us/send_mail' => 'static_pages#send_contact_mail'

  post '/discussions/:id/leave' => 'discussions#leave'
  post '/discussions/:id/enter' => 'discussions#enter'
  post '/discussions_users/:id/confirm' => 'discussions_users#confirm'

  post '/visual_aids/:id/open' => 'visual_aids#open'
  post '/visual_aids/:id/command' => 'visual_aids#command'
  post '/visual_aids/:id/close' => 'visual_aids#close'
  get '/discussions/:id/arguments' => 'discussions#arguments'
  delete 'visual_aids/:id' => 'visual_aids#destroy'

  get '/user_leaved/:id' => 'discussions#user_leaved'
  get '/user_entered/:id' => 'discussions#user_entered'

  get '/assets/faye-browser-min.js.map' => ->(*){ [200, {}, [""]] }
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :contact
  has_many :discussions
  belongs_to :research_institute
  has_many :user_relations
  has_many :users, through: :user_relations

  accepts_nested_attributes_for :contact
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_action :new_company, only: :create
  load_and_authorize_resource


  def show
  end

  def new
    @company = Company.new contact: Contact.new
  end

  def edit
  end

  def create
    respond_to do |format|
      if @company.save
        format.html { redirect_to '/profile', notice: 'Das Unternehmen wurde erfolgreich angelegt.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to '/profile', notice: 'Das Unternehmen wurde erfolgreich aktualisiert.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to '/profile' }
      format.json { head :no_content }
    end
  end


  private

  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:name, contact_attributes: [:street, :postalcode, :town, :email, :telephone])
  end

  def new_company
    @company = Company.new(company_params)
  end
end

app/views/companies/_form.html.erb
<%= form_for(@company, html: { class: 'form-horizontal' }) do |f| %>
  <%= render partial: "shared/error_messages", locals: { resource: @company } %>

  <div class="form-group">
    <div class="field">
      <%= f.label :name, "Name", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: "form-control", autofocus: true %>
      </div>
    </div>
  </div>

  <%= f.fields_for :contact, @company.contact  do |contact_form| %>
    <%= render partial: 'contacts/fields', locals: { f: contact_form } %>
  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-large btn-primary" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= link_to 'Abbrechen', profile_path %>
    </div>
  </div>

<% end %>

app/views/companies/_list.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Straße</th>
    <th>Stadt</th>
    <th>E-Mail</th>
    <th>Telefon</th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% companies.each do |company| %>
    <tr>
      <td><%= company.name %></td>
      <td><%= company.contact.street %></td>
      <td><%= company.contact.postalcode %> <%= company.contact.town %></td>
      <td><%= company.contact.email %></td>
      <td><%= company.contact.telephone %></td>

      <td><%= link_to 'Bearbeiten', edit_company_path(company), class: "btn btn-xs btn-primary" %></td>
      <td><%= link_to 'Löschen', company, method: :delete, data: { confirm: 'Sind Sie sicher?' }, class: "btn btn-xs btn-primary" %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate companies, renderer: BootstrapPagination::Rails, param_name: 'companies_page' %>

app/views/companies/edit.html.erb
<% title 'Unternehmen bearbeiten' %>
<h1>Unternehmen bearbeiten</h1>

<%= render 'form' %>

app/views/companies/new.html.erb
<% title 'Neues Unternehmen anlegen' %>
<h1>Neues Unternehmen anlegen</h1>

<%= render 'form' %>

app/views/companies/show.html.erb
<%# nothing yet, route disabled %>
<%#= render partial: 'contacts/show', locals: { contact: @research_institute.contact } %>